# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- dev

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '528ca8e8-c518-4970-8e21-ef20432d2c58'
  imageRepository: 'mytourweb'
  containerRegistry: 'dinnomytour.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  group: ACR-Credentials

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: 'test'

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: DeployToVM
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: SSH@0
      inputs:
        sshEndpoint: 'TestVM-SSH'  # Use the SSH Service Connection Name
        runOptions: 'commands'
        commands: |  
          echo $(ACR_PASSWORD) docker login dinnomytour.azurecr.io -u $(ACR_USERNAME) --password-stdin        
          docker pull dinnomytour.azurecr.io/mytourweb:test
          docker stop mytour-web || true
          docker rm mytour-web || true
          docker run -d -p 3004:5173 --name mytour-web dinnomytour.azurecr.io/mytourweb:test
          docker system prune -f
        failOnStderr: true        
